### ISSUE TITLE
Fatal Error after update cli into sfdx-cli/7.1.4

### ISSUE THREAD

**Issue by idanblich** [wadewegner/salesforce-cli-zsh-completion#11]
After update to : sfdx-cli/7.1.4 and run ./generate.sh 
completion stop working with this error : 
``` 
sfdx fo
_sfdx:139: parse error near `<'
_sfdx:139: parse error near `<'
_sfdx:139: parse error near `<'

```

**Comment by wadewegner** [comment]
Thanks, I’ll take a look.

**Comment by douglascayers** [comment]
Hi @wadewegner, the fix for me was to escape the double-quotes in the command names/descriptions. Simple change available in https://github.com/wadewegner/salesforce-cli-zsh-completion/pull/12

Thanks
