### ISSUE TITLE
parse error near `<' on sfdx TAB

### ISSUE THREAD

**Issue by rsoesemann** [wadewegner/salesforce-cli-zsh-completion#13]
I installed everything according to the doc but when I type and press tab I always get those parse errors:
```
 robert@Roberts-MacBook-Pro  ~  sfdx for
_sfdx:139: parse error near `<'
_sfdx:139: parse error near `<'
_sfdx:139: parse error near `<'
 robert@Roberts-MacBook-Pro  ~  sfdx for
```

**Comment by siddharatha** [comment]
I face the same issue, i deleted the file and regenerated which lead to 
`
_sfdx:10: unknown file attribute: C

_sfdx:10: unknown file attribute: C
_sfdx:10: unknown file attribute: C`

#12 solved this problem. I directly cloned this repo's develop branch and it solved the problem for me.

**Comment by muenzpraeger** [comment]
Errors even with the branch from @dougcayers now with the Summer version.

_sfdx:1894: parse error near `)'

**Comment by DNLZ** [comment]
@muenzpraeger try loading `_sfdx` in #12 using `unfunction _sfdx && autoload -U _sfdx` without running `./generate.sh` first. Using the new `_sfdx` file in the pr fixed the issue for me, but using the new `generate.sh` still generated a bad file on my system.
